### PR TITLE
fix: reserv width for AppHeader, transparent-border for non-actives

### PR DESCRIPTION
**Pull request by gularsson**

### CODE REVIEW

**Review by dannelundqvist — CHANGES_REQUESTED** [review]
Probably not related to these changes but the app header does not align horizontally with the view header. Either way, it would be nice to fix. Other than that it's great!

**Comment by gularsson** [comment]
> Probably not related to these changes but the app header does not align horizontally with the view header. Either way, it would be nice to fix. Other than that it's great!

Did with two views, but not one, header width varies 57px (aligns) 53px(doesn't align). I'll fixate that tomorrow.

**Comment by gularsson** [comment]
I set a fixed height for the ViewHeader so it wont resize depending on it's content. Should keep the borders aligned.

**Review by dannelundqvist — APPROVED** [review]
Perf!

**Pull request merged**
